name: papirus-extra-folders
build-base: core24
base: bare
version: '2025-12-05'
platforms:
  all:
    build-on: [amd64]
    build-for: [all]
summary: All extra Papirus icon folders
description: |
  A Snap that allows you to use all the extra Papirus icon theme folders in Snap applications
grade: stable
confinement: strict

slots:
  icon-themes:
    interface: content
    source:
      read:
        - $SNAP/usr/share/icons/Papirus-Adwaita
        - $SNAP/usr/share/icons/Papirus-Adwaita-Dark
        - $SNAP/usr/share/icons/Papirus-Adwaita-Light
        - $SNAP/usr/share/icons/Papirus-Black
        - $SNAP/usr/share/icons/Papirus-Black-Dark
        - $SNAP/usr/share/icons/Papirus-Black-Light
        - $SNAP/usr/share/icons/Papirus-Bluegrey
        - $SNAP/usr/share/icons/Papirus-Bluegrey-Dark
        - $SNAP/usr/share/icons/Papirus-Bluegrey-Light
        - $SNAP/usr/share/icons/Papirus-Breeze
        - $SNAP/usr/share/icons/Papirus-Breeze-Dark
        - $SNAP/usr/share/icons/Papirus-Breeze-Light
        - $SNAP/usr/share/icons/Papirus-Brown
        - $SNAP/usr/share/icons/Papirus-Brown-Dark
        - $SNAP/usr/share/icons/Papirus-Brown-Light
        - $SNAP/usr/share/icons/Papirus-Carmine
        - $SNAP/usr/share/icons/Papirus-Carmine-Dark
        - $SNAP/usr/share/icons/Papirus-Carmine-Light
        - $SNAP/usr/share/icons/Papirus-Cyan
        - $SNAP/usr/share/icons/Papirus-Cyan-Dark
        - $SNAP/usr/share/icons/Papirus-Cyan-Light
        - $SNAP/usr/share/icons/Papirus-Darkcyan
        - $SNAP/usr/share/icons/Papirus-Darkcyan-Dark
        - $SNAP/usr/share/icons/Papirus-Darkcyan-Light
        - $SNAP/usr/share/icons/Papirus-Deeporange
        - $SNAP/usr/share/icons/Papirus-Deeporange-Dark
        - $SNAP/usr/share/icons/Papirus-Deeporange-Light
        - $SNAP/usr/share/icons/Papirus-Green
        - $SNAP/usr/share/icons/Papirus-Green-Dark
        - $SNAP/usr/share/icons/Papirus-Green-Light
        - $SNAP/usr/share/icons/Papirus-Grey
        - $SNAP/usr/share/icons/Papirus-Grey-Dark
        - $SNAP/usr/share/icons/Papirus-Grey-Light
        - $SNAP/usr/share/icons/Papirus-Indigo
        - $SNAP/usr/share/icons/Papirus-Indigo-Dark
        - $SNAP/usr/share/icons/Papirus-Indigo-Light
        - $SNAP/usr/share/icons/Papirus-Magenta
        - $SNAP/usr/share/icons/Papirus-Magenta-Dark
        - $SNAP/usr/share/icons/Papirus-Magenta-Light
        - $SNAP/usr/share/icons/Papirus-Nordic
        - $SNAP/usr/share/icons/Papirus-Nordic-Dark
        - $SNAP/usr/share/icons/Papirus-Nordic-Light
        - $SNAP/usr/share/icons/Papirus-Orange
        - $SNAP/usr/share/icons/Papirus-Orange-Dark
        - $SNAP/usr/share/icons/Papirus-Orange-Light
        - $SNAP/usr/share/icons/Papirus-Palebrown
        - $SNAP/usr/share/icons/Papirus-Palebrown-Dark
        - $SNAP/usr/share/icons/Papirus-Palebrown-Light
        - $SNAP/usr/share/icons/Papirus-Paleorange
        - $SNAP/usr/share/icons/Papirus-Paleorange-Dark
        - $SNAP/usr/share/icons/Papirus-Paleorange-Light
        - $SNAP/usr/share/icons/Papirus-Pink
        - $SNAP/usr/share/icons/Papirus-Pink-Dark
        - $SNAP/usr/share/icons/Papirus-Pink-Light
        - $SNAP/usr/share/icons/Papirus-Red
        - $SNAP/usr/share/icons/Papirus-Red-Dark
        - $SNAP/usr/share/icons/Papirus-Red-Light
        - $SNAP/usr/share/icons/Papirus-Teal
        - $SNAP/usr/share/icons/Papirus-Teal-Dark
        - $SNAP/usr/share/icons/Papirus-Teal-Light
        - $SNAP/usr/share/icons/Papirus-Violet
        - $SNAP/usr/share/icons/Papirus-Violet-Dark
        - $SNAP/usr/share/icons/Papirus-Violet-Light
        - $SNAP/usr/share/icons/Papirus-White
        - $SNAP/usr/share/icons/Papirus-White-Dark
        - $SNAP/usr/share/icons/Papirus-White-Light
        - $SNAP/usr/share/icons/Papirus-Yaru
        - $SNAP/usr/share/icons/Papirus-Yaru-Dark
        - $SNAP/usr/share/icons/Papirus-Yaru-Light
        - $SNAP/usr/share/icons/Papirus-Yellow
        - $SNAP/usr/share/icons/Papirus-Yellow-Dark
        - $SNAP/usr/share/icons/Papirus-Yellow-Light
parts:
  icon-themes:
    plugin: dump
    source: https://github.com/Kyuyrii/papirus-extra-folders/releases/download/$SNAPCRAFT_PROJECT_VERSION/snap-files-extra-folders_$SNAPCRAFT_PROJECT_VERSION.deb
    organize:
      usr/share/icons: usr/share/icons
    prime:
      - usr/share/icons
